name: build-pipeline
on:
  workflow_dispatch:
    inputs:
      target:
        required: false
        default: 'target'
env:
  targetPath: ${{ github.event_name == 'push' && format('target') || github.event.inputs.target }}

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build the application
      run: mvn package

    - name: Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: ${{ env.targetPath }}
